---
- name: Dev Environment
  hosts: all
  gather_facts: true
  become: yes

  tasks:
    - name: Base applications
      apt:
        name: [
          "git",
          "tmux",
          "vim"
        ]
        state: present
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
        - apt
        - core_apps

    - name: "Install Ansible pre-reqs"
      become: yes
      apt:
        name: software-properties-common
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
        - apt
        - ansible

    - name: "Install Ansible key"
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 93C4A3FD7BB9C367
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
        - apt
        - ansible

    - name: "Add Ansible repository"
      become: yes
      apt_repository:
        repo: ppa:ansible/ansible
        state: present
        codename: "{{ ansible_distribution_release }}"
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
        - apt
        - ansible

    - name: "Update apt cache"
      become: yes
      apt:
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
        - apt
        - ansible

    - name: "Install ansible"
      become: yes
      apt:
        name: [
          "ansible",
          "ansible-lint"
        ]
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
        - apt
        - ansible

    - name: "Install docker pre-reqs"
      become: yes
      apt:
        name: [
          "apt-transport-https",
          "ca-certificates",
          "curl",
          "gnupg-agent",
          "python3",
          "python3-pip",
          "software-properties-common"
        ]
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
        - apt
        - docker

    - name: "Install docker repository key"
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
        - apt
        - docker

    - name: "Install docker repository"
      become: yes
      apt_repository:
          repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
          state: present
          update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
        - apt
        - docker

    - name: "Install docker"
      become: yes
      apt:
        name: [
          "docker-ce",
          "docker-ce-cli",
          "containerd.io"
        ]
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
        - apt
        - docker
...